server:
  port: 0

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:tc:postgresql:16:///order_test
    username: test
    password: test
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}

eureka:
  client:
    enabled: false
